name: tele_consult
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  footer: ^0.0.4
  flutter_rating_bar: ^4.0.1
  calendar_builder: ^0.0.6
  table_calendar: ^3.0.8
  firebase_auth: ^4.1.2
  firebase_core: ^2.4.0
  pinput: ^2.2.31
  cloud_firestore: ^4.0.5
  firebase_database: ^10.0.15
  fluttertoast: ^8.1.1
  sizer: ^2.0.15
  intl: ^0.17.0
  flutter_admin_scaffold: ^1.1.2
  image_picker: ^0.8.6+1
  responsive_builder: ^0.6.3
  firebase_core_web: ^2.2.2
  firebase_auth_web: ^5.2.9
  flutter_screenutil: ^5.7.0
  file_picker:
  zego_uikit_prebuilt_call: ^3.3.13
  firebase_messaging: ^14.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: "Rubik"
      fonts:
        - asset: "assets/fonts/Rubik-Bold.ttf"
        - asset: "assets/fonts/Rubik-Regular.ttf"
        - asset: "assets/fonts/Rubik-Italic.ttf"
        - asset: "assets/fonts/Rubik-Medium.ttf"
#        - asset: "fonts/Rubik-500.ttf"
#          style: "normal"
#          weight: 500
#        - asset: "fonts/Rubik-regular.ttf"
#          style: "normal"
#          weight: 400
#        - asset: "fonts/Rubik-700.ttf"
#          style: "normal"
#          weight: 700
#        - asset: "fonts/Rubik-regular.ttf"
#          style: "normal"
#          weight: 800
#    - family: "PT Sans"
#      fonts:
#        - asset: "fonts/PTSans-regular.ttf"
#          style: "normal"
#          weight: 400
#        - asset: "fonts/PTSans-700.ttf"
#          style: "normal"
#          weight: 700
#    - family: "Inter"
#      fonts:
#        - asset: "fonts/Inter-regular.ttf"
#          style: "normal"
#          weight: 400
